project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "."
base_url: "https://api.crowdin.com"
preserve_hierarchy: true
commit_message: "l10n(%two_letters_code%): New translations `%original_file_name%` from Crowdin"
append_commit_message: false
pull_request_title: "l10n: New Crowdin updates"
pull_request_labels":
  - "crowdin"
  - "l10n"

languages_mapping: &languages_mapping
  two_letters_code:
    zh-CN: zh-cn
    zh-TW: zh-tw
    pt-BR: pt-br

files:
  - source: "source/api/*.md"
    translation: "/source/%two_letters_code%/api/%original_file_name%"
    update_option: update_as_unapproved
    type: fm_md
    languages_mapping: *languages_mapping

  - source: "source/docs/*.md"
    translation: "/source/%two_letters_code%/docs/%original_file_name%"
    update_option: update_as_unapproved
    type: fm_md
    languages_mapping: *languages_mapping

  - source: "source/*.md"
    translation: "/source/%two_letters_code%/%original_file_name%"
    update_option: update_as_unapproved
    type: fm_md
    languages_mapping: *languages_mapping
