[build]
  command = "npm run build"
  publish = "/public"
  environment = { NODE_VERSION = "14", NODE_ENV = "production" }

[[redirects]]
  from = "/"
  to = "/zh-tw/"
  status = 302
  conditions = {Language = ["zh-tw", "zh-hk"]}
  force = true

[[redirects]]
  from = "/"
  to = "/zh-cn/"
  status = 302
  conditions = {Language = ["zh", "zh-cn"]}
  force = true

[[redirects]]
  from = "/"
  to = "/ru/"
  status = 302
  conditions = {Language = ["ru"]}
  force = true

[[redirects]]
  from = "/"
  to = "/ko/"
  status = 302
  conditions = {Language = ["ko"]}
  force = true

[[redirects]]
  from = "/"
  to = "/pt-br/"
  status = 302
  conditions = {Language = ["pt-br"]}
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Feature-Policy = "accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; camera 'none'; display-capture 'none'; document-domain 'none'; encrypted-media 'none'; fullscreen 'self'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture 'none'; speaker 'none'; sync-xhr 'none'; usb 'none'; vibrate 'none'; wake-lock 'none'; webauthn 'none'"
