description: An elegant Material Design theme for Hexo, based on MDUI.
link: https://github.com/niemingzhao/niemingzhao.github.io/tree/theme
preview: http://www.niemingzhao.top/
tags:
  - Material Design
  - elegant
  - responsive
  - simple
  - clean
repository:
  is_archived: false
  stars: 57
  last_commit_date: '2025-07-21T16:12:31Z'
