<!-- GitHub star -->
<a class="github-button" href="https://github.com/hexojs/hexo" target="_blank" aria-label="Star hexojs/hexo on GitHub" alt="Star"><img src="https://img.shields.io/github/stars/hexojs/hexo?style=social"></a>
<!-- GitHub fork -->
<a class="github-button" href="https://github.com/hexojs/hexo/fork" target="_blank" aria-label="Fork hexojs/hexo on GitHub"><img src ="https://img.shields.io/github/forks/hexojs/hexo?style=social" alt="Fork"></a><!-- Tweet button -->
<!-- Twitter follow button -->
<a href="https://twitter.com/hexojs" class="twitter-follow-button" target="_blank" data-show-count="true" alt="Follow @hexojs"><img src="https://img.shields.io/twitter/follow/hexojs?style=social"></a>

