name: Crowdin Upload Translations

on:
  workflow_dispatch:
    inputs:
      auto_approve_imported:
        description: "Automatically approves uploaded translations"
        default: false
        type: boolean
        required: false
      import_eq_suggestions:
        description: "Defines whether to add translation if it is equal to source string in Crowdin project"
        default: false
        type: boolean
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  upload-translation:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1 # Should be 1 to avoid parallel builds
      matrix:
        lc: [ko, pt-BR, ru, th, zh-CN, zh-TW] # Target languages https://developer.crowdin.com/language-codes/
    steps:
      - uses: actions/checkout@v4

      - uses: crowdin/github-action@v2
        with:
          upload_sources: false
          push_sources: false

          upload_translations: true
          push_translations: false
          download_translations: false
          create_pull_request: false

          upload_language: ${{ matrix.lc }}
          auto_approve_imported: ${{ inputs.auto_approve_imported || false }}
          import_eq_suggestions: ${{ inputs.import_eq_suggestions || false }}

          crowdin_branch_name: ${{ github.ref_name }}
          config: "crowdin.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
