name: Crowdin Upload Sources

on:
  workflow_dispatch:

  push:
    branches:
      - "master"
    paths:
      - "source/about/*.md"
      - "source/api/*.md"
      - "source/docs/*.md"
      - "source/*.md"
      - ".github/workflows/crowdin-upload.yml"
      - "./crowdin.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  upload-source:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1 # Should be 1 to avoid parallel builds
    steps:
      - uses: actions/checkout@v4

      - uses: crowdin/github-action@v2
        with:
          upload_sources: true
          push_sources: false

          upload_translations: false
          push_translations: false
          download_translations: false
          create_pull_request: false

          crowdin_branch_name: ${{ github.ref_name }}
          config: "crowdin.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
